### ISSUE TITLE
Session context lost after restarted

### ISSUE THREAD

**Issue by kitt1987** [warm-metal/cliapp-session-gate#1]
Minikube clusters need to synchronize time after hosts wake up. It leads to API access timeout and SessionGate exit. See logs below.
```
panic: Get "https://10.24.0.1:443/apis/core.cliapp.warm-metal.tech/v1/cliapps": dial tcp 10.24.0.1:443: i/o timeout

goroutine 1 [running]:
github.com/warm-metal/cliapp-session-gate/pkg/gate.(*terminalGate).init(0xc0002f73e0)
	/go/src/cliapp-session-gate/pkg/gate/gate.go:80 +0x29d
github.com/warm-metal/cliapp-session-gate/pkg/gate.PrepareGate(0xc0001e4fc0)
	/go/src/cliapp-session-gate/pkg/gate/gate.go:30 +0x76
main.main()
	/go/src/cliapp-session-gate/cmd/main.go:24 +0xcc
```

**Comment by kitt1987** [comment]
Fixed after using kube-systemd
